# Generated by Django 5.2.12 on 2026-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0013_order_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Set when food is ready (e.g. 4, A2). Shown to customer on track page.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(choices=[('received', 'Order received'), ('queue', 'Waiting list'), ('preparing', 'Preparing in kitchen'), ('ready', 'Ready — assign table'), ('serving', 'Chef bringing to table'), ('delivered', 'Delivered / completed')], default='received', max_length=20),
        ),
    ]
