# Generated by Django 5.2.12 on 2026-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0014_order_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='Booking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in / pre-order at table'), ('delivery', 'Home delivery')], default='dine_in', max_length=20),
        ),
    ]
